#page title
page_title                                : ConvoBeat                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6472098256                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/id6472098256                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : ConvoBeat                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 5.99                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Make meetings more fun.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Karma
your_link                                 : https://www.codewithkarma.com
your_city                                 : Brisbane
email_address                             : karm.singh@outlook.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : codewithkarma
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Elevate meetings
    description                           : Elevate your meetings, presentations, or simply enhance your entertainment setup with a stunning display of background images, customizable titles, and dynamic descriptions.
    fontawesome_icon_name                 : heart
    
  - title                                 : Instant Mirroring
    description                           : Effortlessly mirror your iPhone screen to your Apple TV with a single tap. Enjoy real-time synchronization of content, ensuring a lag-free and immersive experience
    fontawesome_icon_name                 : camera

  - title                                 : Customizable Background
    description                           : Personalize your Apple TV display with a wide range of background images. Choose from a curated collection or upload your own high-resolution images for a truly unique setup.
    fontawesome_icon_name                 : wallet

  - title                                 : Title and Description Settings
    description                           : KConfigure a dynamic title for your mirrored content, making it easy for viewers to identify the context. Add detailed descriptions to provide additional information or set the tone for your presentation or entertainment.
    fontawesome_icon_name                 : eye

  - title                                 : Apple Music Integration
    description                           : Elevate your experience by seamlessly playing Apple Music from your iPhone to your Apple TV. Control playback, adjust volume, and create the perfect audio backdrop for your content.
    fontawesome_icon_name                 : tag

  - title                                 : Real-Time Updates
    description                           : Make changes on the fly – update background images, titles, descriptions, and timers in real time. Keep your content fresh and adapt to the evolving needs of your audience without interrupting the mirroring experience.
    fontawesome_icon_name                 : camera
  
  - title                                 : Optimized for Meetings and Presentations
    description                           : Ideal for business meetings and presentations, ConvoBeat ensures a professional and engaging visual experience. Impress clients and colleagues with a polished display of information and dynamic content.
    fontawesome_icon_name                 : camera

  - title                                 : Secure and Private
    description                           : ConvoBeat prioritizes your privacy and security, ensuring a secure connection between your devices. Share content confidently, knowing that your data remains private and protected.
    fontawesome_icon_name                 : camera

faqs                                      :

  - title                                 : How do I search for a receipt?
    description                           : You can use receipt, store, tag or product name to search for a receipt on the home screen.
    fontawesome_icon_name                 : search

  - title                                 : Installed app on a new device and it is not showing my data?
    description                           : Sometime iCloud does not trigger the refresh. Navigate to Settings -> Apple Id Account -> iCloud. After that just come back to the app and you should see the data.
    fontawesome_icon_name                 : users

  - title                                 : Do I loose all my images if I delete the app?
    description                           : No, when you create receipt using camera, the images are also saved in your photo library and this way you always have the images with you even after deleting the app. Also, the iCloud sync is ON for the app and if you have not turned it off then your data is saved on iCloud always.
    fontawesome_icon_name                 : eraser

  - title                                 : How do I delete a receipt?
    description                           : You can navigate to All receipts page and can swipe to delete a receipt.
    fontawesome_icon_name                 : trash

  - title                                 : How do I create/delete a store?
    description                           : While creating a receipt, when you navigate to store page, you can create a new store or swipe to delete an existing store.
    fontawesome_icon_name                 : trash

  - title                                 : How do I create/delete a tag?
    description                           : While creating a receipt, when you navigate to tags page, you can create a new tag or swipe to delete an existing tag.
    fontawesome_icon_name                 : trash

  - title                                 : Can I select multiple tags?
    description                           : Yes, you can select multiple tags
    fontawesome_icon_name                 : tag

  - title                                 : How do I contact for support?
    description                           : You can post on the twitter @ReceiptsC and I will try to respond. 
    fontawesome_icon_name                 : users

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
